### 회원 생성
POST http://localhost:8080/member
Content-Type: application/json

{
  "name": "신성수",
  "phoneNumber": "01020834409",
  "birthDay": "19950918",
  "balance": "1000"
}

### 계좌 해지
PUT http://localhost:8080/account
Content-Type: application/json

{
  "accountNumber": "0000000001",
  "memberId": "1"
}

### 계좌 생성
POST http://localhost:8080/account
Content-Type: application/json

{
  "memberId": "1",
  "balance": "1000"
}

### 계좌 조회
GET http://localhost:8080/account/1


### 입금
POST http://localhost:8080/deposit
Content-Type: application/json

{
  "memberId": "1",
  "accountNumber": "0000000002",
  "amount" : "100000"
}

### 출금
POST http://localhost:8080/withdraw
Content-Type: application/json

{
  "memberId": "1",
  "accountNumber": "0000000002",
  "amount" : "10"
}

### 지불
POST http://localhost:8080/pay
Content-Type: application/json

{
  "memberId": "1",
  "accountNumber": "0000000002",
  "amount" : "100"
}

### 결제 취소
POST http://localhost:8080/cancel
Content-Type: application/json

{
  "transactionId": "3",
  "accountNumber": "0000000002",
  "amount" : "100"
}

### 거래내역 조회
GET http://localhost:8080/transaction?transaction_id=3
