### 회원 생성
POST http://localhost:8080/member
Content-Type: application/json

{
  "name": "신성수",
  "phoneNumber": "01020834409",
  "birthDay": "19950918",
  "password": "1111"
}

### 계좌 해지
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "accountNumber": "0020220613122617"
}

### 계좌 생성
POST http://localhost:8080/account
Content-Type: application/json

{
  "name": "신성수1",
  "phoneNumber": "01020834409",
  "birthDay": "19950918",
  "password": "1111"
}

### 입금
POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountNumber": "0020220613123610",
  "amount" : "100000"
}

### 출금
POST http://localhost:8080/withdraw
Content-Type: application/json

{
  "accountNumber": "0020220613123610",
  "amount": "1000",
  "password": "1111"
}

### 지불
POST http://localhost:8080/pay
Content-Type: application/json

{
  "accountNumber": "0020220613123610",
  "orderName": "아이폰 14",
  "amount": "1000",
  "password": "1111"
}

### 결제 취소
POST http://localhost:8080/cancel
Content-Type: application/json

{
  "orderId": "3",
  "accountNumber": "0020220613123610",
  "password": "1111"
}

### 거래내역 조회
GET http://localhost:8080/transaction?accountNumber=0020220613123610&page=0&size=10
